#!/bin/bash

# First list the directory with efivars, and check whether they exist:
# Redirect stdout and stderr to /dev/null
ls /sys/firmware/efi/efivars > /dev/null 2>&1
efivarscheck=$?

if [ $efivarscheck -eq 2 ] 
then
	echo "The system uses BIOS boot!"
elif [ $efivarscheck -eq 0 ]
then
	echo "The system uses UEFI boot!"
fi

