#!/bin/bash

user="iakop"
devpc="devpc"
devpath="MyGitRepos/arch-install"

proceed="no"
while [ $proceed != "yes" ]; do
	echo -n "Please enter user password: "
	read -s password
	echo
	# Check if the ftp password is correct by just establishing connection. Before removing anything!
	# FIXME: Need to avoid downloading index all the time!
	curl "ftp://$user:$password@$devpc" >/dev/null 2>&1
	connectioncheck=$?
	if [ $connectioncheck -eq 0 ]; then
		proceed="yes"
		echo "Correct password!"
	else
		proceed="no"
		echo "Incorrect password, try again!"
	fi
done

if [ -d "test" ]; then
	echo "test directory already exists!"
else
	echo "Making test directory..."
	mkdir "test"
fi
if [ -d "packages" ]; then
	echo "packages directory already exists!"
else
	echo "Making packages directory..."
	mkdir "packages"
fi

# Remove any old versions:
archinstall="arch-install"
archinstallpath="./$archinstall"

ftphack="ftphack"
ftphackpath="./$ftphack"

testpci="testpci"
testpcipath="test/$testpci"

packageslist="packages.list"
packageslistpath="packages/$packageslist"

aurpackageslist="aur-packages.list"
aurpackageslistpath="packages/$aurpackageslist"

chrootstep="chroot-step"
chrootsteppath="./$chrootstep"

# wget the new version over ftp:
curl "ftp://$user:$password@$devpc/$devpath/$archinstallpath" > $archinstallpath
curl "ftp://$user:$password@$devpc/$devpath/$ftphackpath" > $ftphackpath
curl "ftp://$user:$password@$devpc/$devpath/$testpcipath" > $testpcipath
curl "ftp://$user:$password@$devpc/$devpath/$packageslistpath" > $packageslistpath
curl "ftp://$user:$password@$devpc/$devpath/$aurpackageslistpath" > $aurpackageslistpath 
curl "ftp://$user:$password@$devpc/$devpath/$chrootsteppath" > $chrootsteppath

# Ensure the new version is executable:
chmod 755 $archinstallpath
chmod 755 $ftphackpath
chmod 755 $chrootsteppath
