#!/bin/bash

pkgname="iptables"

################
# Package check
################
pacman -Qs $pkgname >/dev/null 2>&1
retval=$?
if [ $retval -ne 0 ]; then
	echo "Missing package $pkgname! Exiting."
	exit 1
fi

################
# Configuration
################
# check if iptables rules are already set:
if [ -f /etc/iptables/iptables.rules ]; then
	echo "Rules are already set."
else
	echo "Setting default empty rules for iptables."
	cp /etc/iptables/empty.rules /etc/iptables/iptables.rules
fi

###############
# End of config
###############
# Enable service:
echo "Enabling $pkgname service..."
systemctl enable iptables.service >/dev/null 2>&1
retval=$?
if [ $retval -ne 0 ]; then
	echo "Error enabling service! exiting."
	exit 1
fi

echo "Done!"
