#!/bin/bash

pkgname="openssh"

################
# Package check
################
pacman -Qs $pkgname >/dev/null 2>&1
retval=$?
if [ $retval -ne 0 ]; then
	echo "Missing package $pkgname! Exiting."
	exit 1
fi

###############
# End of config
###############
# Enable service:
echo "Enabling sshd service..."
systemctl enable sshd.service >/dev/null 2>&1
retval=$?
if [ $retval -ne 0 ]; then
	echo "Failed enabling sshd service (Error code: $retval). Exiting."
	exit 1
fi
echo "Done!"
