#!/bin/bash
# Paths used in install script
# Author: Jacob Bechmann Pedersen
# Date: 2020-03-07

# Includes
shared="shared"
sharedpath="$prefix/include/$shared"
functions="functions"
functionspath="$prefix/include/$functions"

# Source includes:
source $functionspath

# Development mode variables:
devusername="iakop"
devhostname="archdev"

# Installer script paths:
archinstall="arch-install"
archinstallpath="$prefix/$archinstall"
chrootstep="chroot-step"
chrootsteppath="$prefix/$chrootstep"

# Config:
config="config"
configpath="$prefix/$config"

# Test files:
testpci="testpci"
testpcipath="test/$testpci"

# Info doesn't exist before the installer runs:
if [ ! -d "$prefix/info" ]; then
	mkdir "$prefix/info"
fi

# Environment and settings info:
configinfo="config.info"
configinfopath="$prefix/info/$configinfo"
envinfo="env.info"
envinfopath="$prefix/info/$envinfo"
tzinfo="tz.info"
tzinfopath="$prefix/info/$tzinfo"
bootinfo="boot.info"
bootinfopath="$prefix/info/$bootinfo"
diskinfo="disk.info"
diskinfopath="$prefix/info/$diskinfo"

# Package lists:
packageslist="packages.list"
packageslistpath="$prefix/packages/$packageslist"
ucodelist="ucode.list"
ucodelistpath="$prefix/packages/$ucodelist"
graphicsinstall="graphics.list"
graphicsinstallpath="$prefix/packages/$graphicsinstall"

# Keys for keychain:
aurkeys="aur.keys"
aurkeyspath="$prefix/keys/$aurkeys"

# Misc. configurations:
configscriptspath="$prefix/configscripts/"
applicationspath="$prefix/applications/"